<?php

/**
 * @file
 * Installs the necessary table for the Variable Price product features.
 */

/**
 * Implementation of hoook_schema()
 */
function uc_varprice_schema() {
  $schema = array();

  $schema['uc_varprice_products'] = array(
    'fields' => array(
      'vpid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'pfid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'price_default' => array(
        'description' => 'Default product price.',
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
      ),
      'price_minimum' => array(
        'description' => 'Minimum product price.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'price_maximum' => array(
        'description' => 'Maximum product price.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'add_to_cart_title' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'amount_title' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
    ),
    'indexes' => array(
      'pfid' => array('pfid'),
    ),
    'primary key' => array('vpid'),
  );

  return $schema;
}

/**
 * Implements hook_uninstall().
 */
function uc_varprice_uninstall() {
  db_delete('uc_product_features')
    ->condition('fid', 'varprice')
    ->execute();
}

/**
 * Migrate uc_varprice variables to config.
 */
function uc_varprice_update_1000() {
  $config = config('uc_varprice.settings');
  $config->set('uc_varprice_global_default', update_variable_get('uc_varprice_global_default', '0'));
  $config->save();

  update_variable_del('uc_varprice_global_default');
}

/**
 * Convert product class defaults to config.
 */
function uc_varprice_update_1001() {
  foreach (node_type_get_names() as $type => $name) {
    $config = config('uc_varprice.settings');
    $data = update_variable_get('ucvp_class_def_' . $type);
    if (!empty($data)) {
      $data = unserialize($data);
    }
    $config->set('class_definitions.' . $type, $data);
    $config->save();

    update_variable_del('ucvp_class_def_' . $type);
  }
}